name: Send Webhook to SecureCodeBox Controller

on:
  push:
    branches:
      - master

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send webhook to SecureCodeBox Controller
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        REPO_URL: ${{ github.event.repository.clone_url }}
        REPO_NAME: ${{ github.event.repository.name }}
        SCANNER: "gitleaks"
        SCANNER_CONFIG: |
          apiVersion: "execution.securecodebox.io/v1"
          kind: Scan
          metadata:
            name: "repo-scan"
            namespace: "securecodebox-scanner"
            annotations:
              metadata.scan.securecodebox.io/git-repo-url: "https://repo_url.com"
          spec:
            scanType: "gitleaks"
            volumes:
              - name: repo
                emptyDir: {}
            volumeMounts:
              - name: repo
                mountPath: "/repo/"
            initContainers:
              - name: "git-clone"
                image: bitnami/git
                volumeMounts:
                  - name: repo
                    mountPath: "/repo/"
                command:
                  - git
                  - clone
                  - "--mirror"
                  - "https://repo_url.com"
                  - /repo/
                env:
                  - name: GITHUB_TOKEN
                    value: "repo_access_token"
            parameters:
              - "detect"
              - "--source"
              - "/repo/"
      run: |
        curl -X POST $WEBHOOK_URL \
          -H "Content-Type: application/json" \
          -d '{
                "repository": {
                  "clone_url": "'"$REPO_URL"'",
                  "name": "'"$REPO_NAME"'"
                },
                "scanner": "'"$SCANNER"'",
                "scanner_config": "'"$SCANNER_CONFIG"'",
                "token": "'"${{ secrets.GIT_TOKEN }}"'"
              }'

    - name: Send webhook to another URL
      env:
        WEBHOOK2_URL: "https://webhook.site/11c30a6a-4054-4cc4-bc95-a40e38f866d5"
        REPO_URL: ${{ github.event.repository.clone_url }}
        REPO_NAME: ${{ github.event.repository.name }}
        SCANNER: "gitleaks"
        SCANNER_CONFIG: |
          apiVersion: "execution.securecodebox.io/v1"
          kind: Scan
          metadata:
            name: "repo-scan"
            namespace: "securecodebox-scanner"
            annotations:
              metadata.scan.securecodebox.io/git-repo-url: "https://repo_url.com"
          spec:
            scanType: "gitleaks"
            volumes:
              - name: repo
                emptyDir: {}
            volumeMounts:
              - name: repo
                mountPath: "/repo/"
            initContainers:
              - name: "git-clone"
                image: bitnami/git
                volumeMounts:
                  - name: repo
                    mountPath: "/repo/"
                command:
                  - git
                  - clone
                  - "--mirror"
                  - "https://repo_url.com"
                  - /repo/
                env:
                  - name: GITHUB_TOKEN
                    value: "repo_access_token"
            parameters:
              - "detect"
              - "--source"
              - "/repo/"
      run: |
        curl -X POST $WEBHOOK2_URL \
          -H "Content-Type: application/json" \
          -d '{
                "repository": {
                  "clone_url": "'"$REPO_URL"'",
                  "name": "'"$REPO_NAME"'"
                },
                "scanner": "'"$SCANNER"'",
                "scanner_config": "'"$SCANNER_CONFIG"'",
                "token": "'"${{ secrets.GIT_TOKEN }}"'"
              }'
